name: Build and Deploy to S3
on:
  push:
    branches: [master]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: yarn install

      - name: Build the UI-library Storybook
        run: yarn build-storybook

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload files to S3 with AWS CLI
        run: |
          aws s3 sync storybook-static/ s3://${{ secrets.S3_BUCKET }} --delete 