name: Licenses CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  reuse:
    name: REUSE Compliance Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fsfe/reuse-action@v1.1
